//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "department")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub department_id: Uuid,
    pub name: String,
    pub founding_date: DateTime,
    pub dean: String,
    pub create_at: DateTime,
    pub update_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::major::Entity")]
    Major,
}

impl Related<super::major::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Major.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
