//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod department;
pub mod major;
pub mod major_department_user;
pub mod sea_orm_active_enums;
pub mod user;
pub mod wallet;
