//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::department::Entity as Department;
pub use super::major::Entity as Major;
pub use super::user::Entity as User;
pub use super::user_major::Entity as UserMajor;
pub use super::wallet::Entity as Wallet;
